---

- name: Install DotNet Environment
  dnf:
    name: dotnet-sdk-5.0
    state: present

- name: Fetch the App from Remote
  git:
    repo: 'https://foosball.example.org/path/to/repo.git'
    dest: /tmp/automationexerciseapp

- name: Publish the App
  command: dotnet publish --configuration Release /tmp/automationexerciseapp/src/AutomationExercise.csproj

- name: Copy Published App to Server
  copy:
    src: "{{ item }}"
    dest: /var/www/automationexerciseapp
    owner: apache
    group: apache
    mode: '0644'
  with_fileglob:
    - /tmp/AutomationExercise/src/bin/Release/net5.0/publish/*

- name: Create a Service for App
  template: 
    src: kestrel-automationexerciseapp.service
    dest: /etc/systemd/system/kestrel-automationexerciseapp.service

- name: Start the Service
  service: 
    name: kestrel-automationexerciseapp.service
    state: started
    enabled: yes

- name: Restart the Server
  service: 
    name: httpd
    state: restarted
